# Generated by Django 3.1.6 on 2023-06-29 15:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RampLoadProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('random_id', models.CharField(default=main.models.unique_rand, max_length=7, null=True, unique=True)),
                ('load_elec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=None)),
                ('sum_load_elec', models.FloatField(null=True)),
                ('ispublic', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, null=True)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('P', models.FloatField(null=True)),
                ('num_windows', models.PositiveSmallIntegerField(default=1)),
                ('window_1_start', models.TimeField(null=True)),
                ('window_1_end', models.TimeField(null=True)),
                ('window_2_start', models.TimeField(default='00:00')),
                ('window_2_end', models.TimeField(default='00:00')),
                ('window_3_start', models.TimeField(default='00:00')),
                ('window_3_end', models.TimeField(default='00:00')),
                ('r_w', models.PositiveSmallIntegerField(default=0)),
                ('func_time', models.PositiveSmallIntegerField(null=True)),
                ('r_t', models.PositiveSmallIntegerField(default=0)),
                ('func_cycle', models.PositiveSmallIntegerField(default=1)),
                ('occasional_use', models.PositiveSmallIntegerField(default=100)),
                ('wd_we', models.PositiveSmallIntegerField(choices=[(0, 'Nur Wochentags'), (1, 'Nur am Wochenende'), (2, 'Die ganze Woche lang')], default=2)),
                ('ramploadprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ramploadprofile')),
            ],
        ),
    ]
