# ./docker-compose.yml

version: '3.9'

networks:
  ramp_network:
    driver: bridge

services:
  ramp_proxy:
    image: nginx:mainline-alpine
    container_name: ramp_nginx
    # build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ramp_web_root:/var/www/html
    depends_on:
      - web
    networks:
      - ramp_network
  ramp_db:
    image: postgres
    container_name: ramp_postgres
    environment:
      - POSTGRES_DB=ramp_app
      - POSTGRES_USER=${DB_ADMIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - ramp_network
    volumes:
      - ramp_postgres_data:/var/lib/postgresql/data
# Django
  web:
    build: .
    container_name: ramp_django
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost web
      - DB_HOST=ramp_db
      - SQL_ENGINE=django.db.backends.postgresql
      - DB_NAME=ramp_app
      - DB_USER=${DB_ADMIN}
      - DB_PASS=${DB_PASSWORD}
    depends_on:
      - ramp_db
    networks:
      - ramp_network

volumes:
  ramp_web_root:
    driver: local
  ramp_postgres_data:
    driver: local


