# ./docker-compose.yml

version: '3.9'

networks:
  ramp:
    driver: bridge

services:
  proxy:
    image: nginx:mainline-alpine
    container_name: nginx
    # build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - web_root:/var/www/html
    depends_on:
      - web
    networks:
      - ramp
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=ramp_app
      - POSTGRES_USER=${DB_ADMIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - ramp
    volumes:
      - postgres_data:/var/lib/postgresql/data
# Django
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=localhost web
      - DB_HOST=db
      - SQL_ENGINE=django.db.backends.postgresql
      - DB_NAME=ramp_app
      - DB_USER=${DB_ADMIN}
      - DB_PASS=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - ramp

volumes:
  web_root:
    driver: local
  postgres_data:
    driver: local


